---
### group_vars/DC1_NETWORK_SERVICES.yml

tenants: # dynamic_key: network_services
  - name: MY_FABRIC
    l2vlans:
      - id: 10
        name: 'HQ1-CORP-USERS'
        tags: [hq_floor1]
      - id: 11
        name: 'HQ1-VOICE'
        tags: [hq_floor1]
      - id: 12
        name: 'HQ1-PRINTERS'
        tags: [hq_floor1]

      # ===== HQ Floor 2 access domain =====
      - id: 20
        name: 'HQ2-CORP-USERS'
        tags: [hq_floor2]
      - id: 21
        name: 'HQ2-VOICE'
        tags: [hq_floor2]
      - id: 22
        name: 'HQ2-CONF-AV'
        tags: [hq_floor2]

      # ===== Shared everywhere =====
      - id: 99
        name: 'CAMPUS-GUEST-WIFI'
        tags: [campus_all]

# Incase SVIs lie on the Spines (l3spine)

# tenants:
#   - name: MY_FABRIC
#     vrfs:
#       - name: default
#         vrf_id: 10
#         svis:
#           - id: 10
#             name: 'HQ1-CORP-USERS'
#             tags: [hq_floor1]
#             enabled: true
#             ip_virtual_router_addresses:
#               - 10.10.10.1
#             nodes:
#               - node: SPINE1
#                 ip_address: 10.10.10.2/24
#               - node: SPINE2
#                 ip_address: 10.10.10.3/24
#           - id: 20
#             name: 'HQ2-CORP-USERS'
#             tags: [hq_floor2]
#             enabled: true
#             ip_virtual_router_addresses:
#               - 10.20.20.1
#             nodes:
#               - node: SPINE1
#                 ip_address: 10.20.20.2/24
#               - node: SPINE2
#                 ip_address: 10.20.20.3/24